### ISSUE TITLE
Finalizing whole libraries at a time?

### ISSUE THREAD

**Issue by ffMathy** [AArnott/pinvoke#104]
Is there any pattern to how we write the PInvoke classes? It doesn't seem like there are any of the libraries that are 100% done yet.

Wouldn't it be a good idea to finish entire DLL imports for whole DLL files at a time, for instance finishing _user32.dll_ first before working on others?

To use this library, I need to know that it has everything I need before downloading it. As long as it isn't 100% done, I am not using it (due to the fear of something missing).

Also, I think there are some areas that are more used than others (for instance shell32.dll, kernel32.dll and user32.dll). Could we start with these?

**Comment by AArnott** [comment]
> To use this library, I need to know that it has everything I need before downloading it. As long as it isn't 100% done, I am not using it (due to the fear of something missing).

I don't see why it's crucial that it has _everything_ you need in order to use it at all. It's hardly mutually exclusive that you can either write P/Invokes yourself or use this library. You can do both. If you had 20 P/Invoke methods you needed and this library provided some of them, then that's some of them that you don't have to write yourself.
Of course, you can then write the missing ones in your own project. But per the contribution doc, you can choose to write those extra ones in this library and consume it _immediately_ (not even waiting for your PR to be accepted) in your own project and thus this project grows organically based on the popularity of its APIs.

In my opinion, it is a _non_-goal to complete user32.dll or kernel32.dll. There simply isn't a need for some of these APIs. Take gdi32.dll for example: the only reasonable consumer for the full set of APIs in it would be someone writing a graphics framework like WinForms (not even WPF would use most of them). And catering to such an odd scenario isn't a productive use of active contributors' time. Focusing on APIs folks actually use will help more folks in general. And that might mean we have an average of 20% coverage of most libraries.

> I think there are some areas that are more used than others (for instance shell32.dll, kernel32.dll and user32.dll). Could we start with these?

Any contributor that wants to add methods is of course very welcome to do so. So far, the active contributors we have have tended to add methods based on what they personally consume, which I think is a good model to follow because it will naturally grow based on demand/popularity of the APIs.

In the case of small, focused libraries such as BCrypt, I'm personally interested in reaching 100% coverage because I'll use most or all of them in PCLCrypto and 100% is a nice round number so I'd be willing to reach a bit further to finish it off.
