### ISSUE TITLE
Build error (that doesn't break the build?) in Create-PInvokeTxtFile.ps1

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#122]
From [this AppVeyor build](https://ci.appveyor.com/project/AArnott/pinvoke/build/1.0.369)

```
PInvoke.Win32 -> C:\projects\pinvoke\bin\Release\Packages\PInvoke.Win32.0.1.286-beta-ge68a656187.nupkg
 420  C:\projects\pinvoke\tools\Create-PInvokeTxtFile.ps1 : Cannot bind argument to 
 421  parameter 'AssemblyPath' because it is an empty string.
 422  At line:1 char:68
 423  + & { & 'C:\projects\pinvoke\src\..\tools\Create-PInvokeTxtFile.ps1' '' }
 424  +                                                                    ~~
 425      + CategoryInfo          : InvalidData: (:) [Create-PInvokeTxtFile.ps1], Pa 
 426     rameterBindingValidationException
 427      + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAl 
 428     lowed,Create-PInvokeTxtFile.ps1
 429   
 430  CodeGeneration.Debugging -> C:\projects\pinvoke\src\CodeGeneration.Debugging\bin\Release\CodeGeneration.Debugging.exe
```

I wonder if this is because the specialized build scripts aren't prepared to skip processing of the code generation projects.

**Comment by jmelosegui** [comment]
Two things here:
1. The build should fail if the powershell command fails to execute.
2. We need to improve the MSBuild condition for including the PInvoke.Extra.targets file in the build process.

##### First point.

I don't know why the Exec task can't see that error (maybe because powershell.exe does not set a proper exit code?). As a workaround I can set to `true` the property [LogStandardErrorAsError](https://msdn.microsoft.com/en-us/library/microsoft.build.utilities.tooltask.logstandarderroraserror.aspx)  to catch the error.

##### Second point.

This is happening since we added the `PInvoke.Win32` NuProj project and the error is caused due to an empty `$(TargetPath)` variable. So we should do something like:

```
Condition=" !$(MSBuildProjectName.Contains('Test')) AND $(TargetPath) != '' "
```

Instead of

```
Condition=" !$(MSBuildProjectName.Contains('Test')) AND !$(MSBuildProjectName.Contains('NuGet'))  "
```

to exclude any project without a `$(TargetPath)` (NuProj so far) regardless the name. 

I wouldn't complicate more that condition to exclude the CodGen projects since they don't have any `[DLLImport]` decorated method and the increased time for processing those project is only on the build server (since we have the `GeneratePInvokeTxt` build parameter).
