### ISSUE TITLE
Avoid regressing target platform consumption

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#234]
We have [several issues](https://github.com/AArnott/pinvoke/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22target+platform+consumption%22+) from various platforms being unable to consume PInvoke.\* libraries.

We should have a way to catch and avoid such regressions before they enter the product, particularly since fixing some of them require API breaking changes (such as #232).

**Classes of issues observed**
1. Xamarin.Android cannot build in Release configuration #232 
2. Xamarin.iOS cannot build for _device_ when linking framework SDKs #232 
3. UWP cannot build in Release configuration due to a bug in the .NET Native toolchain #227 
4. PInvoke package accidentally bundles extra assemblies (e.g. CodeGeneration) leading to references that break Xamarin.Android #230
5. UWP build produces warnings because NuGet package dependencies include packages not available on UWP #226

**Requirements to avoid such regressions**
1. Validate that a project targeting each supported platform can consume each of our packages.
2. Validate that APIs are strict supersets and subsets across the supported platforms and portable profiles for each package, such that we don't have weird incompatible APIs across platforms (e.g. on desktop and portable we define a type that derives from distinct types depending on platform.)

**Comment by vbfox** [comment]
It seem that it could have been detected by having the build compile an executable that reference our library (potentially calling all APIs) with at least one Xamarin platform & UWP.

_The "potentially calling all APIs" is there because we might want to ensure that all of our types / methods are referenced at least once to avoid the build succeeding because some optimization phase dropped the type/method but it wouldn't have compiled. I don't know UWP or Xamaring enough to assert if it is a real problem or not._

It will slow the build so it might need to be in separate builds (Can be done in parallel with the main one) but it would have shown most of the problems.

**Comment by AArnott** [comment]
So far, it seems that both UWP and Xamarin linkers will catch all issues, whether or not they will be linked in. So for now at least "calling all APIs" is probably/hopefully overkill and we could get by simply by compiling an app that references it, and uses at least one of its APIs such that an assembly reference is created.

While we might simply have a project for each platform that references the PInvoke projects directly, part of the useful testing is actual consumption of the NuGet packages, to ensure that they'll be installed properly, without extra assemblies, etc. 
I've written this sort of package consumption testing in xunit actually, where the unit test will install the package that was just built into a template project, then build it, to ensure it works as expected. Perhaps we can apply a similar set of tests here.

**Comment by arlm** [comment]
Just a dumb question. Why one would put a Win32 Kerlne32.dll PINvoke inside an Android, or iOS application? What good it can bring?

IMHO if the person really needs something to work cross-platform there should be an interface and different implementations targeting each platform.

It doesn't make any sense Win32 PInvoke outside of Windows environment.

**Comment by AArnott** [comment]
@arlm: it's not obvious, but there are actually uses for it on non-Win32 platforms.

Many of these functions _are_ allowed in Store apps, and quite useful. For `PInvoke.*` to be used in Store apps they have to be 'portable', which makes them applicable to Xamarin platforms as well. So we do it primarily for UWP -- not for Xamarin. 

But even so, there are non-Windows OS interests here:
1. Linux and OSX do or may have `Wine` installed, which makes P/Invoke to a Win32 API interesting there too.
2. P/Invoke libraries may define structs that are very much applicable on other platforms. The common example in my own use is cryptographic key format structures: they are spec'd in RFCs and apply regardless of platform. So yes, even on Xamarin.Android and Xamarin.iOS, I use the PInvoke libraries at least for the structs.

But yes, I avoid calling the Win32-only functions on these platforms.

**Comment by arlm** [comment]
Good to know.

Regarding item 1. I always thought that using wine to PInvoke on OSX and Linux involved much more than asking for the DLL. People at Mono had it working ion the beginning but let it go now for many years because wine was a moving target and did not map/implement the subtle aspects of the APIs making stuff behave weirdly and have noticeable differences on stack/memory management. On top of it I thought that wine should be running spawned by the C# process in order to achieve reachability through PInvoke. Have you ever used it this way or know someone that did?

I work with/develop in mono for Linux/OSX since 2003 and have never heard of someone that was successful on integrating mono with wine.

**Comment by AArnott** [comment]
No, for no. 1 I was speaking theoretically.
But I'm surprised to hear wine is so bad. I thought the point was that it let apps run unmodified on Linux. So this requirement that special steps be taken within the program itself is surprising. 
But ya, no. 2 is the one I personally use.

**Comment by arlm** [comment]
For no. 1:
- [Why Mono people tried to integrate wine and ditched this support after some time](http://www.mono-project.com/docs/gui/winforms/#history)
- Wine has a [mono-wine bridge](https://wiki.winehq.org/Mono) since version 1.5.3 (and it [seems to still being supported](https://github.com/madewokherd/wine-mono)), but I suppose it behaves as it is on Windows when running and do not report being on any platform different than Windows.
- I'm pretty sure that this works only if the .exe/.dll was started by wine, then it can access the modified mono runtime to use the PInvokes but if you are running on regular mono directly over the operation system it won't start wine to do the PInvoke call.

**Comment by arlm** [comment]
Thinking about all this. Your use makes sense and is nice/clever. What I think that bothers me is having the PInvoke calls open to be called on an environment in which it will certainly fail (and probably not so graciously).

I thought that might be a proposed solution:
- Having the full-fledged Desktop version as we already have
- Having the portable subsets that have compatible calls as we already have, but removing xamarin.android and xamarin.ios support from those. (If there is a portable code to target Linux and Mac OS X running Mono it should be out also)
- Having a new package (or set of packages) called PInvoke.Abstract.\* or PInvoke.Types.\* that are true portable among all platforms that contains those helpers, structures and types that are useful anywhere as you have pointed.

It might pose a big refactoring effort but it would ensure we don't have any kind of improper use of the libraries. It also would not trigger any checkers that in the future might be used to ensure platform compatibility and would complain about foreign PInvoke calls. Stuff like [MoMA - Mono Compatibility Checker](http://www.mono-project.com/docs/tools+libraries/tools/moma/)

**Comment by AArnott** [comment]
Thanks for the background on Wine. I've written off any expectation of PInvoke.\* working on Wine.

AFAIK there is no way in a NuGet package to avoid targeting Xamarin platforms. They opt themselves into various other (Windows) profiles by claiming "hey, my profile is compatible with profile259" for example. Since we target 259, 111, it means Xamarin is included. Even if we manually removed the Xamarin TxM's from the lib folder of our packages, they'd still be seen as compatible with Xamarin in at least some scenarios. You can also see this expressed when setting the target platforms for a profiles-based PCL: the dialog won't let you leave Xamarin targets unchecked -- it will 'helpfully' say "Hey, we see that Xamarin platforms will not change the surface area so we'll just add that back for you."

Also: a portable library can't predict what OS it may run on. But it can do runtime checks and branch logic based on that. If PInvoke simply removed the APIs for PCLs that _might_ run on non-Windows platforms, these consuming PCLs wouldn't have the option to call PInvoke within a Windows-specific branch of their code.

Finally, consider the downlevel Windows OS case. PInvoke libraries [may] have APIs for functions that were added in Windows 10. That means if code blindly calls them while running on Windows 8, it will fail. Should PInvoke have reference assemblies for every version of Windows so that we don't expose P/Invoke functions new in Win10 unless your app is targeting Win10? That _sounds_ like a great idea from a consumer's perspective, but it's technically infeasible, since NuGet has no concept of targeting OS versions -- only framework versions.

Thus, it's impossible for the reference assemblies exposed by PInvoke packages to have exactly the set of APIs that would succeed for some intended target OS. Reaching some approximation of it through a large amount of work can possibly cut too much or too little, depending on what the consumer is trying to do. Instead of offering a muddy and frustrating story, our charter/scope is to provide the P/Invoke signatures and supporting types. The caller is still responsible to read documentation and call them at appropriate times. Just as if they didn't have this library. It's just easier with the library because the caller of course doesn't have to author the method signatures and types, and in many cases we give them xml doc comments.

Does that make sense?
