### ISSUE TITLE
User32.GetWindowRect not showing up on a .NET 4.0 app

### ISSUE THREAD

**Issue by robsonfelix** [AArnott/pinvoke#265]
Some methods are not showing up although I can see them in the code tree. Any ideas why?

**Comment by vbfox** [comment]
The version on NuGet is 0.3.2 from April and `GetWindowRect` only appeared following PR #240 on May 13 so there is still no release containing this code.

I'm not sure why there wasn't any release since then, @AArnott is the one doing the releases and he'll have more info but he commented 4 days ago in #264 about a release occurring soon.

In the mean time it's possible to add the AppVeyor feed and get the latest nightly as described in the contributor document : https://github.com/AArnott/pinvoke/blob/master/CONTRIBUTING.md#self-service-releases-for-contributors .

**Comment by AArnott** [comment]
Thanks for the investigation, @vbfox. Yes, I'll execute a release very soon.
Let's have a discussion on gitter about a good release cadence.

**Comment by AArnott** [comment]
0.3.90 is publishing to nuget.org [now](https://ci.appveyor.com/project/AArnott/pinvoke/deployment/363576).

**Comment by robsonfelix** [comment]
hey guys, that definitely fixed it! I am still missing the following functions...

GetWindowText
SetCursorPos
GetCursorPos
EnumDesktopWindows
WindowFromPoint
EnumWindows
GetWindowPlacement

Are they not part of User32.dll?

**Comment by AArnott** [comment]
@robsonfelix: we don't have p/invoke signatures for those functions yet. We would certainly accept a PR to add them.
