### ISSUE TITLE
Add NativeErrorCode in Win32Exception.Message

### ISSUE THREAD

**Issue by NN---** [AArnott/pinvoke#333]
Consider adding NativeErrorCode in the exception message.
Greatly improves debugging and logs reading.

For instance
```cs
class Win32Exception
{
 // Return original Message with the code
 public override string Message => $"{base.Message} ({NativeErrorCode})";
}
```

Another option is to hack "_message" property to not store the same message twice and get free serialization.

**Comment by AArnott** [comment]
If this diverges from the behavior of `Win32Exception` on .NET Framework, that's not inline with the goal for this class. If `Win32Exception` behavior varies between platforms that can ultimately cause unexpected issues for consumers.
So while I don't challenge the value that you're proposing, PInvoke's charter is not to improve on `Win32Exception`. We only implement it in the first place because PCL profiles don't define it themselves.
