### ISSUE TITLE
Kernel32.DeviceIoControl(...) signature wrong

### ISSUE THREAD

**Issue by nefarius** [AArnott/pinvoke#349]
The parameters `dwIoControlCode` and `pBytesReturned` should be `uint` instead of `int`:

```Csharp
public static extern unsafe bool DeviceIoControl(
    SafeObjectHandle hDevice,
    int dwIoControlCode,
    void* inBuffer,
    int nInBufferSize,
    void* outBuffer,
    int nOutBufferSize,
    out int pBytesReturned,
    OVERLAPPED* lpOverlapped);
```

The [native signature](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363216(v=vs.85).aspx) uses `DWORD` which translates to `UInt32` in .NET

**Comment by AArnott** [comment]
This is actually intentional. You are right, of course, but there's no binary incompatibility here from the difference in integer types. Both are 32-bit. The only difference would be if the value exceeded `int.MaxValue`, in which case it would overflow to a negative number. If that's a concern for you (and it very rarely is) you can cast the result to `uint` and be good as new.

The reason we use `int` instead of `uint` is so that in the vast majority case, it saves you from having to cast to `int` yourself in order to actually use this in any .NET API which almost universally uses `int` instead of `uint`.

**Comment by nefarius** [comment]
I see, thank you very much for the quick response!
