### ISSUE TITLE
Include all APIs in netstandard builds

### ISSUE THREAD

**Issue by StephenCleary** [AArnott/pinvoke#382]
I'm trying to consume `PInvoke.Kernel32` from a `netstandard` library, but it does not include the desktop APIs.

I believe PInvoke should include *all* APIs in its `netstandard` builds, because Microsoft has taken the position of "assume you can do anything on netstandard, and it may just break at runtime". Not a direction I agree with, but it's the one they're taking.

(In my case, if the library is running on Windows, it'll be in a desktop app anyway).

**Comment by AArnott** [comment]
One problem we must be careful of is that if your netstandard library ships with a UWP app, it will fail certification in the Store if it contains p/invoke signatures to desktop-only APIs, even if you don't call them.

Now maybe we could include them all in netstandard and then compile for UWP without them, so that netstandard can see them but UWP explicitly can't, and a UWP app will (hopefully) package up the library that omits desktop only APIs. I'm not positive that will work though. And I also wonder why a netstandard library would want to see desktop only apis. If you want to target desktop, why not just target desktop?

**Comment by StephenCleary** [comment]
Ah, I'm not very familiar with UWP dev. From a Nuget perspective, you'd have to include a binary that is "closer" to UWP than netstandard is. Based on [this](http://nugettoolsdev.azurewebsites.net/4.3.0-preview4/get-nearest-framework?project=uap10.0&package=netstandard1.1%0D%0Aportable-net45%2Bwin80%2Bwpa81), it appears that the PCL binary would be considered "closer", so if you continue to keep the desktop APIs out of the PCL build (and only include them in netstandard), it should work.

My use case is a netstandard library that can be used on either Unix or Windows. It's a library for Console apps to adhere to Docker conventions. On Windows (currently), the only way to detect a graceful Docker shutdown is via P/Invoke. While it's _possible_ to install my library into a Desktop (.NETFramework) app, that would be weird. I'd expect it to be installed in a `netcoreapp` project. (I am considering changing my library to target `netcoreapp`, but it would still consume the `netstandard` version of `PInvoke.Kernel32`).

**Comment by AArnott** [comment]
[That's](http://nugettoolsdev.azurewebsites.net/4.3.0-preview4/get-nearest-framework?project=winrt&package=net45%0D%0Anet40%0D%0Anet20%0D%0Anetstandard1.1%0D%0Aportable-net40%2Bwin8%2Bwpa81%0D%0Aportable-net45%2Bwin8%2Bwpa81) a neat tool. Thanks for sharing.
Apparently `winrt` would be the best target framework for excluding Store-banned APIs, but it seems the VS 2017 tooling doesn't even support targeting winrt any more. I'm still investigating more. 

Exposing the Store-banned APIs to netstandard but excluding from PCL sounds like it may have a limited lifespan. MS doesn't want to support PCL going forward from what I gather. If they do simply cut support for it, then netstandard would become the next 'best match' and suddenly all the Store apps would be broken, and I'd have to break a bunch of other people to re-omit the APIs.

Still looking through options...

**Comment by StephenCleary** [comment]
Yeah, `winrt` is dead. If this was my project and I had to exclude APIs from Store builds, I would prefer adding a `uap10.0` build that excludes them, and have all the other builds include them.

That should work with one caveat; `netstandard` (and PCL)-based libraries would have the full API set available at build time. But if that library is consumed by a Store app, then the `PInvoke.*.dll` binary would be the more limited Store one, and if there's an API unavailable, they'd get an exception at runtime. But I suppose that makes sense.

**Comment by AArnott** [comment]
`winrt` is not as dead as you might think. I have heard from several customers who target WinRT whenever we accidentally leak a store-banned API into PInvoke.

Anyway, I have it working (the TxMs anyway) but for some reason Roslyn's semantic model won't give me a constant (integer) value for an enum expression, only when the code being analyzed is targeting WinRT (or UAP perhaps). It's causing our codegeneration to fail. I still need to work out why.

**Comment by StephenCleary** [comment]
Sorry, I meant tooling-wise. :)  I had to drop support for that framework from AsyncEx last year for the same reason, and was contacted a few times. But hey, when my laptop failed it was literally not possible to create a new build machine anymore that supported every SDK I needed, so the old platforms had to go...

**Comment by Eran-BenShahar** [comment]
I'm trying to move my team's project to `netstandard` as well and I'm missing the `Job` APIs from `Pinvoke.Kernel32`.
Is there any progress with this?

If you can give me some guidance on what needs to be done, I can maybe continue working on it myself.

**Comment by AArnott** [comment]
Well, `winrt` is [a little deader](https://www.windowscentral.com/microsoft-stop-accepting-new-windows-8-windows-phone-8-app-submissions-soon) now.

I've pushed my `fix382` branch to this repo so you can try taking this on, @EranBE. My hope is still that we don't have to drop `winrt` support. But if neither of us can do it (and I might be willing to try once more), then I guess we can drop it and simplify the problem.

**Comment by AArnott** [comment]
Actually I just remembered -- we certainly cannot remove the `win8` Store target because *all* Store apps (whether for win8 or win10) are rejected by the store if they include APIs that are banned from the Store. So it's not just a matter of winrt vs. uwp.

**Comment by Eran-BenShahar** [comment]
So I played with this a bit and I'm thinking of doing something different.
I suggest we add the `netstandard2.0` TargetFramework as a DesktopOnlyFramework (in addition to `netstandard1.1` which is a PortableOnlyFramework).
The reasons for this is:
- When adding the `desktop\**` files you find out that `netstandard2.0` is required (due to APIs such as `SafeRegistryHandle`, `System.Drawing.Region` etc.)
- Using [this great tool](http://nugettoolsdev.azurewebsites.net/4.3.0-preview4/get-nearest-framework?project=winrt&package=netstandard1.1%0D%0Anetstandard2.0%0D%0Aportable-net40%2Bwin8%2Bwpa81%0D%0Aportable-net45%2Bwin8%2Bwpa81%0D%0Anet45%0D%0Anet40%0D%0Anet20) - you can see that `winrt`, `netcore` and `uap` targets will always select `portable-net45+win8+wpa81` and never `netstandard2.0`.
- This way projects targeting `netstandard2.0` will get the "assume you can do anything on netstandard, and it may just break at runtime" behavior (which is the desired behavior for .Net Core/Standard 2.0+).

I have a PR ready, and all tests pass (except `User32Facts.GetWindowTextHelper_WithNonzeroLastError` which fails on master for me as well).

@AArnott WDYT?

**Comment by AArnott** [comment]
@EranBE What you say sounds very tempting. My concern is that v.next of uap may in fact support .netstandard2.0 (which is relatively new still). So depending on it just happening to work that way isn't a strong guarantee, IMO. I'd love to see your PR. I think we'll need to make sure it actually builds a `winrt` (or `uap`) targeted framework as well though just to make sure that uapX.Y never picks up netstandard2.0 even in the future.

**Comment by Eran-BenShahar** [comment]
@AArnott I agree with what you're saying and I also thought about it.
Unfortunately, I think the only way around future UAP releases moving to `netstandard2.0` and beyond is maybe to create separate NuGets for projects that have store banned APIs. Something like `PInvoke.Kernel32.Nonportable`

**Comment by AArnott** [comment]
Why would they need separate packages? That's what multi targeting is there to support. Multiple packages in fact would not work because as a UAP app that consumes a library that uses these packages, we need those packages to automatically change to drop the store banned apis. That can't happen if the package IDs are different.

**Comment by Eran-BenShahar** [comment]
I went over your PR briefly and it seems like a better & more comprehensive change (which I was reluctant to do since I'm not familiar enough with the entire codebase).
Thanks for picking this up.
Let me know if I can help in any other way.

**Comment by AArnott** [comment]
Thanks. I'm glad you find it adequate. I'm struggling to diagnose the AppVeyor build failures. If you have any insight I'd love to hear it.

**Comment by AArnott** [comment]
I'm making headway in resolving the build breaks, BTW.
