### ISSUE TITLE
Store Banned Methods in .NET Core Apps

### ISSUE THREAD

**Issue by BenjaminHolland** [AArnott/pinvoke#422]
Not all .NET Core Apps are bound by the restrictions of the store, and many important functions (like Kernel32.CreateFile) are missing. 

I can see the reason for having packages that separate compatibility issues, but simply removing those functions from .NET Core damages the usability of the library. Some ideas:
* Provide a PInvoke.*.StoreBanned package that provides these methods on .NET core
* Provide a PInvoke.*.StoreSafe package that only provides the store safe methods, and provide the store banned functions by default.

**Comment by AArnott** [comment]
Splitting the library across redundant packages cause major issues when an app consumes lib A, which consumes the StoreSafe package, and lib B, which consumes the StoreBanned package. Then the app (even without consideration for whether it's a store app) now references *both* pinvoke libraries, causing major headaches to the app author.

Now, you talk about .NET Core apps as if we have special builds for them. We do not. We build specially for Store-targeted apps (we target `win8`), but otherwise we build for netstandard, .NET Framework, and a few PCL profiles. We used to omit the store-banned APIs from the netstandard compilation, but with #382 we made .NET Standard builds include *all* APIs. 

So if you're building a Windows app, the banned APIs will not be there. But everything else you might build will have all APIs available to you. If you write a .NET Standard library and consume a store-banned API, and then your .NET Standard library is consumed by a Store app, the Store app will fail at runtime with a MethodNotFoundException, but it won't be banned from the store on the basis of consuming a banned API (although it might be blocked from the store on the basis of the runtime or binding failure to a missing method).

Does that help?

**Comment by BenjaminHolland** [comment]
Strange. I wasn't able to reproduce the behavior I saw. I'm positive i was building a Core Console app (I haven't played with UWP at all), and the methods wern't showing up, but I just checked and it's fine now.

**Comment by AArnott** [comment]
We shipped the NuGet packages with the change I mentioned only a couple days ago. So perhaps you had the older version.

**Comment by BenjaminHolland** [comment]
Yep. That sounds about right. Thanks!
