### ISSUE TITLE
User32: UnhookWinEvent is missing

### ISSUE THREAD

**Issue by x1unix** [AArnott/pinvoke#457]
Hello, I noticed that [`UnhookWinEvent`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-unhookwinevent) from **User32** is missing.

Can you add please it?

```csharp
[DllImport("user32.dll")]
public static extern bool UnhookWinEvent(IntPtr hWinEventHook);
```

**Comment by AArnott** [comment]
We actually do have it, but it's private because we expect people to use `SafeEventHookHandle`, which is what the public `SetWinEventHook` method returns. 
Are you getting the handle from some other API such that you need direct access to the `IntPtr` method? Would it make sense for you to initialize a `SafeEventHookHandle` object when you get the `IntPtr` another way, and use that, and then close the handle using that object?

**Comment by x1unix** [comment]
@AArnott I had my own package with user32 bindings. Recently discovered this repo and decided to migrate to it (basically replaced all my bindings in favor of pinvoke) and discovered that this function was missing.

**Comment by x1unix** [comment]
@AArnott as you here, can you also consult please regarding `GetMenuItemInfo` (it's related to my project mentioned in issue).

This library unlike another bindings, accepts `char*` for `MENUITEMINFO.dwTypeData` but other bindings use plain string or `IntPtr` (like inside `System.Windows.Forms.MenuItem`) and I faced the issue that I get strange `&` symbol inside menu item labels. I can't figure out what is wrong (tried different encoding marshaling but it didn't work).

I can't find any unit test for `GetMenuItemInfo` in this library to get atleast some clue.
![изображение](https://user-images.githubusercontent.com/9203548/84599264-724ac500-ae79-11ea-91a0-09d76d5dfb48.png)

**Comment by AArnott** [comment]
@x1unix can you open a separate issue to discuss `GetMenuItemInfo`? Let's try to keep each issue's discussion focused. Your comment above would be great to directly copy over to that issue.

Still waiting for your response as to how/whether you can use `SafeEventHookHandle` for this issue.

**Comment by x1unix** [comment]
@AArnott can `safeEventHookHandle.Dispose()` be used instead of `UnhookWinEvent()?`

If yes - this is not so critical but maybe someone will need `UnhookWinEvent` in some exotic situations when messing with some low-level stuff.

Maybe it's worth to mention that hook can be removed in easy way with `.Dispose()` in `SafeEventHookHandle` documentation since this wrapper exists only in this particular library.

**Comment by AArnott** [comment]
Yes, the `SafeEventHookHandle.Dispose` method calls `UnhookWinEvent` internally. It's pretty obvious in the API, IMO, because the APIs that produce handles that need to be unhooked produce `SafeEventHookHandle` instead of `IntPtr`. Since `SafeEventHookHandle` derives from `SafeHandle`, it follows the typical .NET rules for such classes. So I'm not sure where else this would need to be documented.

**Comment by x1unix** [comment]
@AArnott thank you for response :)
