### ISSUE TITLE
Missing documentation file in Nuget packages

### ISSUE THREAD

**Issue by Entomy** [AArnott/pinvoke#524]
Some/all nuget packages don't have documentation files in them, and as a result, intellisense is missing all the documentation that has been provided. This can be resolved by adding in a `<GenerateDocumentationFile>true</GenerateDocumentationFile>` to the `.csproj` files, which will build and copy the file automatically.

![image](https://user-images.githubusercontent.com/25399505/89550402-940c5c80-d7d7-11ea-8174-d596bedb8a97.png)

**Comment by AArnott** [comment]
Wow. We would definitely want to fix this right away. But I'm surprised to hear it because we do in fact set this property for all projects:

https://github.com/dotnet/pinvoke/blob/3c1cf12afee32884de4ac1468e85d7a7bc985fdb/src/Directory.Build.props#L11

Which packages are missing the xml file? A spot check on PInvoke.Windows.Core, PInvoke.User32 and even PInvoke.Kernel32 (which your screenshot shows) show .xml files are in fact present in the package.

Perhaps the problem is the APIs you're specifically looking for. For example, `WriteConsole` from your screenshot does not in fact have any xml doc comments:

https://github.com/dotnet/pinvoke/blob/3c1cf12afee32884de4ac1468e85d7a7bc985fdb/src/Kernel32/storebanned/Kernel32.cs#L2706-L2730

**Comment by Entomy** [comment]
@AArnott Hah, that's what I get for making assumptions. I saw doc comments in so many of the sources I assumed the problem was something else. My bad!
