### ISSUE TITLE
_setmode() and _fileno()

### ISSUE THREAD

**Issue by Entomy** [AArnott/pinvoke#534]
I need [`_setmode`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/setmode?view=vs-2019) and [`_fileno`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fileno?view=vs-2019) for something I'm working on, and would be more than happy to provide the p/invokes back to this library. However I'm having a hard time with where they are located, library wise. As such, attempts to use fail because it can't find the functions. Any idea?

**Comment by AArnott** [comment]
Those methods are not in the Win32 libraries. They are in the C runtime library. If you don't mind your managed application shipping with the C runtime .dll, then I suppose you may be able to p/invoke into it.
However this repo (at least currently) is scoped to p/invokes into the Win32 libraries rather than the C runtime. So this is out of scope.

**Comment by Entomy** [comment]
Ah, I was thinking they weren't because non-standard. But then I supposed that's why there's the `_` prefix. Got it, thanks!
