### ISSUE TITLE
Why does  dotnet/pinvoke use pointers instead of ref/out args?

### ISSUE THREAD

**Issue by fandrei** [AArnott/pinvoke#548]
For instance, the User32.GetMessage function is defined `GetMessage(MSG*, IntPtr, WindowMessage, WindowMessage)` rather than `static extern int GetMessage(out MSG lpMsg, IntPtr hWnd, uint wMsgFilterMin, uint wMsgFilterMax);`
Any motivation for doing it this way?

**Comment by AArnott** [comment]
Because pointers are the original definition and are applicable to _every_ situation. 
That said, we also have what we call "friendly" overloads that are generated during the build that turn pointers into `out` parameters or other applicable modifiers. We don't have any `[Friendly]` attribute on the `GetMessage` method in particular, although we would accept a PR that adds them.
 
As an example, consider the `GetCursorInfo` method, which in the compiled result has 3 overloads:
![image](https://user-images.githubusercontent.com/3548/103724033-a9f19980-4f90-11eb-85f1-46d86ad53763.png)

Even though in source code it has only one definition:

https://github.com/dotnet/pinvoke/blob/4dd1951cfc85248c654ef147897303b2177c15e9/src/User32/User32.cs#L1100-L1103

**Comment by AArnott** [comment]
![image](https://user-images.githubusercontent.com/3548/103723967-7e6eaf00-4f90-11eb-84b1-0ed782bcbb60.png)

**Comment by fandrei** [comment]
@AArnott however, this is not the "good practice" way.

**Comment by AArnott** [comment]
I don't understand. That practice are you saying isn't good?

**Comment by fandrei** [comment]
@AArnott the recommended way is to use ref or out. In fact, I've never seen before anyone using pointers instead.
One difference that comes to my mind is that using pointer args requires to put the call into an unsafe block while ref/out doesn't.

**Comment by AArnott** [comment]
So as is so often the case, "it depends". 
When using `ref` or `out`, you have to have a field or local typed as the exact thing you are receiving. But you may want to instead use memory that is already allocated elsewhere (e.g. native memory) or typed differently (e.g. a byte buffer). Offering pointer overloads ensure that the very most efficient code can be written in all cases. Unsafe code really isn't all that hard to write.
But sure, in the more common and simple cases, `ref`/`out`/`in` overloads are certainly easier to call so we create them wherever we can and where the contributor took the time to decorate the parameter so we know which modifier to replace the pointer with.
