### ISSUE TITLE
User32.EnumDisplayMonitors() cannot be used without unsafe.

### ISSUE THREAD

**Issue by HavenDV** [AArnott/pinvoke#559]
Tested on Windows 10 latest version.
Correct code:
```cs
[DllImport("user32", CharSet = CharSet.Unicode)]
private static extern bool EnumDisplayMonitors(IntPtr hdc, IntPtr lpRect, MonitorEnumProc callback, IntPtr dwData);

private delegate bool MonitorEnumProc(IntPtr hDesktop, IntPtr hdc, ref RECT pRect, IntPtr dwData);
```

**Comment by AArnott** [comment]
First, regarding `EnumDisplayMonitors`, our current definition is:

https://github.com/dotnet/pinvoke/blob/bb42d006da197c6690752111cbfbb70090daa39c/src/User32/User32.cs#L1675-L1677

This strikes me as accurate. Now you're complaint is evidently not that it is wrong but that it uses pointers. That is true, but if you look at our built NuGet package you'll notice that overloads of the method are also offered that do _not_ require the `unsafe` keyword. This is done by our build system, so you will not discover them by looking at the source code alone.

I also note that your proposed `EnumDisplayMonitors` method would malfunction in a 64-bit process because you have the 4th parameter fixed at 4 bytes, when in fact the native function's 4th parameter has a length equal to a pointer size. So you would need to use `IntPtr` for the 4th parameter to behave on a 64-bit process.

Regarding `MonitorEnumProc`, I don't think we generate pointer-free alternatives to delegate types, so it's true you need to use `unsafe` for your delegate. And you're right that using `ref` in the delegate signature would avoid that requirement. 
Offering pointer-free options is a goal of this library, so we should probably think about how our code generation can be used to produce such delegates and reference them in parameters of the methods that take or return them as well.

That all said, when doing interop, using pointers is often not a bad way to go. In fact using pointers in C# is often much easier to get right and less code than using `IntPtr` and the `Marshal` class.

**Comment by HavenDV** [comment]
> I also note that your proposed `EnumDisplayMonitors` method would malfunction in a 64-bit process because you have the 4th parameter fixed at 4 bytes, when in fact the native function's 4th parameter has a length equal to a pointer size. So you would need to use `IntPtr` for the 4th parameter to behave on a 64-bit process.

Yes, my mistake, I fixed the parameter type for the delegate, but forgot to fix it for EnumDisplayMonitors.

I don't see any direct arguments against using unsafe in low-level libraries, but I would still like to avoid it if possible.

**Comment by AArnott** [comment]
>  but I would still like to avoid it if possible.

That's understandable. We'll use this issue to track enhancing our friendly overload code gen to add support for non-pointer delegates as well.

**Comment by GiantappMan** [comment]
Any updates?

**Comment by AArnott** [comment]
No. And unlikely to happen *here* since this repo is largely deprecated in favor of http://github.com/microsoft/cswin32, which is where most of my time spent on interop is going. It too generates friendly overloads so it might make sense to accommodate the request over there. It _might_ even already work, I don't know.

**Comment by GiantappMan** [comment]
Thanks for your reply, I didn't know about the cswin32 until now.
