### ISSUE TITLE
Don't mix helpers and non-helpers

### ISSUE THREAD

**Issue by ffMathy** [AArnott/pinvoke#71]
I don't think it's a good idea to mix helpers and non-helpers in the same class name. Others have no clear indication of when something is a helper method, and typically beforehand they are either looking for the "barebone low-level" native API approach, or a high-level assisted approach to solving a problem.

I say we change the name of the helper classes to something else or use a specific naming convention for helpers, so that people can clearly tell the difference.

Ideally, we could even put the helpers in a separate NuGet package. I never want high-level stuff and I think it pollutes my API if they are mixed.

Imagine 3 packages:
- PInvoke.BCrypt
- PInvoke.BCrypt.Mockables (this one could also be included as discussed other places)
- PInvoke.BCrypt.Helpers

I think that's the right approach and the convention that we see elsewhere.

**Comment by vbfox** [comment]
I think that it should all be only in one package, easier to consume.

But helper code in a separate class is a good idea like `Kernel32Helpers`, their behavior expecially around exception is different from pure P/Invoke so separating them and forcing a `using static PInvoke.Kernel32Helpers;` to get them in scope would clarify things.

The only problem is that it reduce their discoverability (But we can compensate via documentation).

**Comment by ffMathy** [comment]
How about calling the class the same, but putting it in a Helpers namespace? That would also make it easier to discover.

And the IDE will also help with the discovery.

I don't understand your argument in regards to "it is easier to consume one package". What about dependencies? If I install BCrypt.Helpers, it would also install BCrypt. Furthermore, atomic NuGet packages is the convention everywhere (autofac for instance when you need ASP.NET integration).

**Comment by ffMathy** [comment]
I would never use PInvoke if the helpers were included. It seems unclean to me, and I know quite a few that would agree.

Why not just separate the concerns and let people decide?

**Comment by AArnott** [comment]
I don't understand the problem of helpers and non-helpers being in the same class. We're not talking about low level vs. high level library distinctions here as the helper methods have very limited additional functionality (per the guidance doc). We're just talking about additional overloads that rearrange the parameters, change their types, or perform the memory management. 
Also, a helper method alternative is not usually available. So making a separate place to look, only to be disappointed most of the time, seems like a way to set the customer up for frustration.
The way it is designed now, if we have the method supported in the library at all, they'll be guaranteed to find it. Via overloads they'll also discover that there are several options, some more friendly than others. 

General programming guidelines suggest that a class do one thing well. Splitting up exactly the same operation, but different overloads, across multiple classes IMO violates that principle.

**Comment by AArnott** [comment]
> I would never use PInvoke if the helpers were included. It seems unclean to me

Do you really avoid libraries because it offers a method you don't agree with and don't have to call? Are you afraid you'll call it by accident or is it just a principle thing?

**Comment by AArnott** [comment]
To be clear, I'd love to find a way to resolve your concerns. I want to fully understand the problem to see what all our options are that could resolve it.

**Comment by ffMathy** [comment]
I am afraid I will call it by accident first of all, and then I am afraid of the new types, classes and unnecessary logic it introduces. And then, like you think it is unclean to duplicate every method, it feels unclean to me.

Which method do I call? `InstallService` or `CreateService`? If you heard of those two, which one would you think was the high or low level? I find that confusing, which breaks the whole idea of this library.

Programming is often about communicating clearly what everything does, through the code itself. Whether that clear communication is achieved by categorizing our "Helpers" more effectively, I don't know.

PInvoke calls are already very low-level. The users of this library will expect nothing more than being able to call these low-level methods in their own way.

I mean, if we look around (https://www.nuget.org/packages?q=autofac), we see that components typically offer a "core". This "core" solves the basic need of the programmer, and nothing more. Through my career at eBay, I have figured out that the minimal solution is the best.

Let's say we wanted to make our own ArrayList. Instead of adding both a `Remove`, `Add` and `Sort` method on this array list _in case we needed that in the future_, I would start with an `Add` method alone, until **I needed anything else**. I am a fan of not exposing too much "just in case", and give people a choice of what they want to have.

Imagine if AutoFac offered WPF, ASP .NET, Windows Forms and Console Application support in one NuGet package. You don't want that, because that's where the _specifics_ diverge. Here, the specifics diverge as well. We have the basic need from the guy who just wants to get the PInvoke definitions, and then the more high-level guy that needs all the help he can get.

It helps a bit that we separate each package by its API name. But I still think a huge separation of concerns would be high and low-level.

**Comment by ffMathy** [comment]
Also, regarding "looking for a method", I think you might be exaggerating the problem. Every IDE has support for quickly finding classes _containing_ some phrase. Even without ReSharper. If I want a method related to Windows Services, I search for "Service".

But where it is located is not going to be a problem I think, and I would even go as far as saying that it would _solve_ a problem; the problem of what you call and what you **think the code does** from what it communicates via its name.

**Comment by ffMathy** [comment]
Another argument for having a simple "core", is that it is easier to fork for others and do exactly what _they had in mind_, without re-inventing the wheel. If we bundle this library with all kinds of stuff _we think_ the developer needs, this flexibility goes away.

I sure wouldn't want to fork a project with helpers inbuilt, if all I wanted was my own take on how a PInvoke library should be used. I think it is sad that we are stuck with the high-level functions without us needing them, _especially when they are in the same class, and have similar names_.

**Comment by AArnott** [comment]
> And then, like you think it is unclean to duplicate every method, it feels unclean to me.

Let's not put words in my mouth. I don't recall ever saying it felt unclean to duplicate every method. I was concerned about tripling the size of the library.

> Which method do I call? InstallService or CreateService? If you heard of those two, which one would you think was the high or low level? I find that confusing, which breaks the whole idea of this library.

I rather hope that helper methods in general are just overloads to existing methods. So I hope that `InstallService` and `CreateService` are two different functions in the native library, possibly with helper overloads. If one is a helper only and the other is not, then I sympathize with the confusion and we should see what we can do to fix that. The guidance doc is meant to avoid such confusion where it states that helper methods are not supposed to serve as a higher level abstraction to the library, leaving that instead to other projects.
This project shouldn't really introduce high or low level distinctions, but rather make the functionality that is already exported from the native library readily available to the .NET caller. This guidance does not forbid helper methods -- it merely limits what they do to making it easier to access the functionality that is already there (for that one method that it overloads).

> PInvoke calls are already very low-level. The users of this library will expect nothing more than being able to call these low-level methods in their own way.

I think we agree on this point. Again, per the guidance doc, where most callers would have a bunch of boilerplate to write (that can often be wrong as folks doing P/Invoke often don't know how to do it right without a lot of research) a helper method that can serve most callers and reduce risk of bugs in their code is a net benefit.

>  I am a fan of not exposing too much "just in case", and give people a choice of what they want to have.

I agree with this too. We shouldn't just add helper methods for the heck of it, or to change the return type of the method or something trivial like that. This is consistent with the guidance doc. Most of the helper methods I've added, for example, are because in writing a unit test for the P/Invoke method itself I had to write several lines of boilerplate code just to call the method at all, so it's a strong case to be made that no one else could avoid those boilerplate lines either and thus most folks would likely benefit from the helper method. This drive toward helper methods from the unit tests also lead to these helper methods being included in the code coverage of our unit tests, which I think is also important as it raises confidence that this code is also safe to call.

> Imagine if AutoFac offered WPF, ASP .NET, Windows Forms and Console Application support in one NuGet package. You don't want that, because that's where the specifics diverge. Here, the specifics diverge as well. We have the basic need from the guy who just wants to get the PInvoke definitions, and then the more high-level guy that needs all the help he can get.

Yes, this is why the guidance doc prohibits helper methods that cater to a specific use case. For example, we don't want a helper method that makes encrypting JPGs easier but does nothing for encrypting other blobs. But if nearly every single caller, regardless of use case, has to allocate 3 global memory handles, copy structs into them, call the method, then reverse all these operations, a helper method that does all of that, then you're not supporting WPF, ASP.NET, etc in a general purpose library. Rather, in effect we are filling in where .NET interop marshaling falls short. That is the purpose of the helper methods.

> Also, regarding "looking for a method", I think you might be exaggerating the problem. 

A single use case of one of the PInvoke packages already requires two using statements:

``` csharp
using PInvoke;
using static PInvoke.LIBNAME;
```

What is the pattern in your vision for someone who wants to use a library? How would they discover the helper methods when they're about to call `BCryptEncrypt`, for example? Would they have even more `using` statements? What prevents them from using the hardest (original) method when a simpler helper overload would have been exactly what they need for lack of discovery?

>  the problem of what you call and what you think the code does from what it communicates via its name.

So long as the helper methods simply call into P/Invoke and fill in the marshaling that .NET doesn't provide, I think the method signature itself tells what it does. It calls the native function by the matching name and takes the inputs and returns the outputs as specified. Anything more than that and I'd agree we'd probably be raising the abstraction layer a bit too much for the P/Invoke library, or we'd need to at least consider mitigating your concern in another way, perhaps via xml doc comments in the `<summary>`.

> I sure wouldn't want to fork a project with helpers inbuilt, if all I wanted was my own take on how a PInvoke library should be used. I think it is sad that we are stuck with the high-level functions without us needing them, especially when they are in the same class, and have similar names.

If the library was nothing by PInvoke methods (no helpers), what room is there for your "own take on how a PInvoke library should be used"? The goal of this library isn't to help folks fork it to do their own thing (while that's a fine secondary design goal). The primary goal IMO is to bring access to native libraries to .NET developers by doing the tedious and often hazardous work of the P/Invoke interop for them. If you forked a project at all, I suppose it's because you aren't happy with the way it is already. I am having a hard time imagining why the presence of some methods in the project would make you not want to fork a project, as IMO that seems like another reason _to_ fork it (since you're unhappy with it and you might remove them). But I'm more interested in making the project useful to consumers than in making it more attractive for folks to fork and change.
Of course I am interested in making this project attractive to potential contributors as that can help add API coverage and thus help achieve the primary goal of being useful to consumers. This is why I spent so much extra time ensuring that anyone can build the project locally and have the result be exactly what it is in the official builds so they can depend on their own changes immediately (again, as mentioned in the contrib doc).

**Comment by AArnott** [comment]
BTW, if any of my arguments sound reasonable but don't seem consistent with what you see in the code base (such as your `CreateService` and `InstallService` example), we can perhaps redirect our attention at those cases and what we should do to fix or remove them.

Also, your idea of a `PInvoke.LIBNAME.Core` library that has just the P/Invokes and then `PInvoke.LIBNAME` adds the helpers could work too. My only concern with that is whether the C# consuming experience is negatively impacted (e.g. requiring 3 `using` statements). We can give it a try to see how minimal impact we can make it have.

**Comment by AArnott** [comment]
Or maybe separate packages for Core, helpers and mockable interface/class. But then we need to solve the problem of blending mockable interface with helpers.

**Comment by ffMathy** [comment]
Thanks for your clear elaboration. It all makes a lot more sense now, thanks.

I didn't try to put words in your mouth.

I don't think 3 using statements is a problem. Why would it be?

**Comment by AArnott** [comment]
> Thanks for your clear elaboration. It all makes a lot more sense now, thanks.

Great! Lets both look at the guidance doc to see what we can do to make the wording stronger. And consider renaming/removal of inappropriate helper methods prior to the initial stable release. We could retitle this issue to track that or close this and open a new one. 
Agreed? or is there yet some unresolved aspects to this?

> I don't think 3 using statements is a problem. Why would it be?

This may be a moot point now, not sure. Perhaps in the interest of the mockability it's still interesting but if that's the only case we could take up this discussion on that issue.

But since I already wrote up this response, I'll stick it here rather than delete it. :)

Framework design guidelines encourage organizing classes in namespaces such that a single `using` statement is generally sufficient to cover a few related scenarios completely. All I/O is found in one namespace, for example. In .NET cryptography is generally under one namespace. 
WinRT deviates from this and splits crypto into 3+ namespaces and it's more of a pain to get started using it in any given code file as a result.

In my experience, folks tend to either follow up adding an assembly reference with adding a using statement at the top by hand or just typing a type name fully from memory and then using "ctrl+." to activate the "add using" code fix to add the necessary using. After either of these steps, they're generally unblocked to use much of the library, and they expect extension methods to have been imported by that same namespace as well. When additional classes that are highly related and likely to be used in tandem aren't in the same namespace, usability suffers.

**Comment by AArnott** [comment]
It seems we've reached consensus here, and we've updated the guidance doc and even fixed up a helper method or two to conform.
