### ISSUE TITLE
Review existing projects for API Sets support

### ISSUE THREAD

**Issue by AArnott** [AArnott/pinvoke#84]
Our existing libraries should be checked and updated to properly support modern platforms by applying the new [API Sets guidance](https://github.com/AArnott/pinvoke/blob/master/CONTRIB.md#win32-api-sets).

The following projects need to be reviewed:
- [x] AdvApi32
- [x] BCrypt
- [x] DbgHelp
- [x] Gdi32
- [x] Hid
- [x] ImageHlp
- [x] Kernel32
- [x] NCrypt
- [x] Psapi
- [x] SetupApi
- [x] User32

**Comment by jmelosegui** [comment]
@AArnott did you see my https://github.com/AArnott/pinvoke/pull/83#event-476833461 ?

**Comment by AArnott** [comment]
I hadn't yet. Thanks for calling that out. 
Kernel32 still needs [this work](https://github.com/AArnott/pinvoke/commit/3571feb5fd082792c0773763bff939a97411fd7d#commitcomment-14664617)

**Comment by jmelosegui** [comment]
I am working on AdvApi32 which involve 2 new projects AdvApi32 Portable and AdvApi32 Shared.

**Comment by AArnott** [comment]
Thanks, @jmelosegui

**Comment by vbfox** [comment]
I checked psapi and the dll functions were moved to Kernel32 as `K32Xxx` where `Xxx` is the original function name since Windows 7.
We [already redirect](https://github.com/AArnott/pinvoke/blob/master/src/Kernel32.Desktop/Kernel32.cs#L762) theses versions to the correct API set (`api-ms-win-core-psapi-l1-1-0.dll`) so nothing to do there as the dll itself is obsolete on non-desktop anyway.

**Comment by AArnott** [comment]
Great. Thanks.
